language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
install:
  - "pip install -r requirements.txt"
  - "pip install peewee"
  - "pip install coveralls" # for coveralls.io reporting
script:
  - python -m unittest discover tests
  - coverage run --source=fillmydb -m unittest discover tests
after_success:
  - coveralls
